from models import Node, Music
from fastapi import HTTPException
from typing import List

class DoublyLinkedList:
    """DoublyLinkedlist stores music playlist"""
    def __init__(self):
        self.head: Node | None = None
        self.tail: Node | None = None
        self.current: Node | None = None


    def music_in_playlist(self, id: int) -> bool:
        """Check if music id exists in playlist"""
        current = self.head
        while current is not None:
            if current.music.id == id:
                return current
            current = current.next  
        return False


    def play_music(self, id: int):
        if not self.head:
            raise HTTPException(status_code=400, detail='No music in playlist')

        if not (node := self.music_in_playlist(id)):
            raise HTTPException(status_code=400, detail='Music is not in playlist')

        self.current = node
        
    def get_playlist(self) -> List[Music]:
        """Returns a list of music objects generated by traversing playlist"""
        music_list: List[Music] = []

        current = self.head
        while current:
            music_list.append(current.music)  
            current = current.next  
        return music_list


    def add_music(self, node: Node) -> List[Music]:
        """Adds a music object in playlist"""
        if self.music_in_playlist(node.music.id):
            raise HTTPException(status_code=400, detail="Music already in playlist")

        if self.head is None:
            self.head = self.tail = self.current = node
            return self.get_playlist()
        
        self.tail.next = node
        node.prev = self.tail
        self.tail = self.tail.next
        return self.get_playlist()

    def play_next(self):
        """Play music stored in next node"""
        if not self.current:
            raise HTTPException(status_code=400, detail='No music is playing')

        if not self.head:
            raise HTTPException(status_code=400, detail='No music in playlist')
        
        if not self.head.next:
            raise HTTPException(status_code=400, detail='Only one music in playlist')
        
        if self.current.next:
            self.current = self.current.next      

    
    def play_previous(self):
        """Play music stored in previous node"""
        if not self.current:
            raise HTTPException(status_code=400, detail='No music is playing')

        if not self.head:
            raise HTTPException(status_code=400, detail='No music in playlist')
        
        if not self.head.next:
            raise HTTPException(status_code=400, detail='Only one music in playlist')

        if self.current.prev: 
            self.current = self.current.prev

playlist: DoublyLinkedList = DoublyLinkedList()