import json
from fastapi import FastAPI, HTTPException, Depends, APIRouter
from pydantic import BaseModel
from typing import Self, Annotated, List
from functools import lru_cache
from contextlib import asynccontextmanager

@lru_cache(maxsize=1)
def music_db():
    """Reads songs.json file and returns a list of dictionaries"""
    with open('songs.json', 'r') as file:
        return json.load(file)

class Music(BaseModel):
    """Music class represent individual music object in songs.json"""
    id: int
    name: str

class Node(BaseModel):
    """Node used to implement linkedlist"""
    music: Music
    next: Self | None = None

class LinkedList:
    """Linkedlist stores music playlist"""
    head: Node | None = None

    def music_in_playlist(self, id: int) -> bool:
        """Check if music id exists in playlist"""
        current = self.head
        while current is not None:
            if current.music.id == id:
                return True
            current = current.next  
        return False
    
    def get_playlist(self) -> List[Music]:
        """Returns a list of music objects generated by traversing playlist"""
        music_list: List[Music] = []

        current = self.head
        while current is not None:
            music_list.append(current.music)  
            current = current.next  
        return music_list
    
    def play_music(self, input: Music) -> int | None:
        if not self.head:
            self.head = Node(music=input)

        if not self.music_in_playlist(input.id):
            self.head = Node(music=input)
        else:
            return input.id
        
    
    def add_music(self, input: Music) -> List[Music]:
        """Adds a music object in playlist"""
        if self.music_in_playlist(input.id):
            raise HTTPException(status_code=400, detail="Music already in playlist")

        if self.head is None:
            self.head = Node(music=input)
            return self.get_playlist()
        
        current = self.head
        while current.next is not None:
            current = current.next
        current.next = Node(music=input)
        return self.get_playlist()

    def play_next(self):
        """Play music stored in next node"""
        global currently_playing

        if not currently_playing:
            raise HTTPException(status_code=400, detail='No music is playing')

        if not self.head:
            raise HTTPException(status_code=400, detail='No music in playlist')
        
        if not self.head.next:
            raise HTTPException(status_code=400, detail='Only one music in playlist')
        
        current = self.head
        while current.next is not None:
            if current.music.id == currently_playing:
                currently_playing = current.next.music.id
                break
            current = current.next
    
    def play_previous(self):
        """Play music stored in previous node"""
        global currently_playing

        if not currently_playing:
            raise HTTPException(status_code=400, detail='No music is playing')

        if not self.head:
            raise HTTPException(status_code=400, detail='No music in playlist')
        
        if not self.head.next:
            raise HTTPException(status_code=400, detail='Only one music in playlist')
        
        prev: Music | None = None
        current = self.head
        while current is not None:
            if current.music.id == currently_playing and prev:
                currently_playing = prev.music.id
                break
            prev = current
            current = current.next

playlist: LinkedList
currently_playing: int | None

@asynccontextmanager
async def lifespan(app: FastAPI):
    # Initialize global variables
    global playlist
    global currently_playing
    playlist = LinkedList()
    currently_playing = None
    yield

app = FastAPI(lifespan=lifespan)

class MusicId(BaseModel):
    """Payload for add_to_playlist and play_music views"""
    music_id: int

@app.get('/music-list')
def music_list(db: Annotated[List[Music], Depends(music_db)]):
    return db

@app.post('/add-to-playlist')
def add_to_playlist(body: MusicId, db: Annotated[List[Music], Depends(music_db)]):
    music_id: int = body.music_id
    music: Music = Music(**list(filter(lambda x: x["id"] == music_id, db))[0])
    global currently_playing
    if not currently_playing:
        currently_playing = music.id
    return {
        'playlist': playlist.add_music(music),
        'current': currently_playing
    }

@app.post('/play-music')
def play_music(body: MusicId, db: Annotated[List[Music], Depends(music_db)]):
    global currently_playing
    music: Music = Music(**list(filter(lambda x: x["id"] == body.music_id, db))[0])
    ret = playlist.play_music(music)
    if isinstance(ret, int):
        currently_playing = ret
    else:
        currently_playing = body.music_id
    return {
        'playlist': playlist.get_playlist(),
        'current': currently_playing
    }

@app.get('/current-music-playing')
def current_music_playing():
    return {
        'current': currently_playing
    }

@app.get('/play-next')
def play_next():
    playlist.play_next()
    return {
        'current': currently_playing
    }

@app.get('/play-previous')
def play_previous():
    playlist.play_previous()
    return {
        'current': currently_playing
    }

@app.get('/playlist')
def get_current_playlist():
    return playlist.get_playlist()
